# Generated by Django 3.1.3 on 2020-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markets',
            name='address',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
