# Generated by Django 3.1.3 on 2020-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_markets_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markets',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
