# Generated by Django 3.0.7 on 2020-12-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20201206_2256'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
