# Generated by Django 3.0.7 on 2020-12-06 18:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_auto_20201206_2319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
